package cn.decision01.danmakuvote.Enums;

public enum EventEnum {
    WORLD_CHANGE_SUNNY,
    WORLD_CHANGE_STORM,
    WORLD_CHANGE_THUNDER,
    PLAYER_TELEPORT,
    PLAYER_GENERATE_MOBS,
    PLAYER_PUT_ANIMAL,
    PLAYER_FIRE,
    PLAYER_THUNDER,
    BLOCK_DELETE,
    INVENTORY_CLEAR
    /*
    PLAYER_FREEZE,
    PLAYER_INVINCIBLE
     */
}
