package cn.decision01.danmakuvote.Enums;

public enum EventEnum {
    WORLD_CHANGE_SUNNY,
    WORLD_CHANGE_STORM,
    WORLD_CHANGE_THUNDER,
    WORLD_CHANGE_TIME,
    PLAYER_TELEPORT,
    PLAYER_GENERATE_MOBS,
    PLAYER_FIRE,
    PLAYER_THUNDER
}
